from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
import uvicorn
import pandas as pd
import os

app = FastAPI()

# Tell FastAPI where your HTML files are
templates = Jinja2Templates(directory="templates")

LOG_FILE = "logs/alerts.log"

# --- Route 1: Serve the Dashboard HTML ---
@app.get("/", response_class=HTMLResponse)
async def read_dashboard(request: Request):
    return templates.TemplateResponse("dashboard.html", {"request": request})

# --- Route 2: The API that feeds data to the Dashboard ---
@app.get("/api/metrics")
async def get_metrics():
    stats = {
        "total_threats": 0,
        "anomalies_24h": 0,
        "recent_alerts": [],
        "category_counts": {}
    }

    if os.path.exists(LOG_FILE):
        try:
            # Read the logs generated by sniffer.py
            # Columns: Timestamp, Source, Destination, Severity, Method
            df = pd.read_csv(LOG_FILE, names=["Time", "Source", "Destination", "Severity", "Method"])
            
            if not df.empty:
                # 1. KPI Stats
                stats["total_threats"] = int(len(df))
                # For demo, we count 'High' severity as critical anomalies
                stats["anomalies_24h"] = int(len(df[df['Severity'].str.contains("High")]))
                
                # 2. Data for Doughnut Chart (Attack Methods)
                stats["category_counts"] = df['Method'].value_counts().to_dict()
                
                # 3. Data for Table (Last 10 alerts, reversed)
                stats["recent_alerts"] = df.tail(10).to_dict(orient="records")
                
        except Exception as e:
            print(f"Error reading logs: {e}")
            # Return empty stats on error so dashboard doesn't crash
            
    return stats

if __name__ == "__main__":
    # Run the server on localhost:8000
    uvicorn.run("server:app", host="127.0.0.1", port=8000, reload=True)